 // start of arguments for aws_efs_file_system resource 
 variable "creation_token" {
  default =""  
  description ="creation_token - (Optional) A unique name (a maximum of 64 characters are allowed) used as reference when creating the Elastic File System to ensure idempotent file system creation. By default generated by Terraform. See Elastic File System user guide for more information."
 }
 
variable "tags"{
  default = {
    Name = "ereg_efs_for_sftp"
  }
  description ="tags - (Optional) A mapping of tags to assign to the file system."
 }

variable "encrypted"{
  default = true 
  description ="encrypted - (Optional) If true, the disk will be encrypted."
 }
                      
variable "performance_mode"{
  default = "generalPurpose"
  description ="performance_mode - (Optional) The file system performance mode. Can be either generalPurpose or maxIO (Default: generalPurpose)."
 }            

variable "provisioned_throughput_in_mibps"{
   default = null
   type = string
   description ="provisioned_throughput_in_mibps - (Optional) The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with throughput_mode set to provisioned."
 }       

variable "throughput_mode"{
   default = "bursting"
   description ="throughput_mode - (Optional) Throughput mode for the file system. Defaults to bursting. Valid values: bursting, provisioned. When using provisioned, also set provisioned_throughput_in_mibps."
 }       
   
  variable "kms_key_id"  {
    default =""
    description ="kms_key_id - (Optional) The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true."
  }             
  
  variable "transition_to_ia" {
     default ="AFTER_30_DAYS" 
     description ="policy of tranfer files from EFS to infrequent access class storage."
  }
 

// start of arguments for aws_efs_mount_target resource
variable "file_system_id" {
  type = string
  default =""
  description ="file_system_id - (Required) The ID of the file system for which the mount target is intended."
}

variable "mount_target_ip_address" {
 default =""
 type = string
 description ="ip_address - (Optional) The address (within the address range of the specified subnet) at which the file system may be mounted via the mount target."
}

variable "subnets" {
  default =[]
  type= list
  description ="subnet_id - (Required) The ID of the subnet to add the mount target in."
}

variable "security_groups" {
 type = list
 description ="security_groups - (Optional) A list of up to 5 VPC security group IDs (that must be for the same VPC as subnet specified) in effect for the mount target."
}

variable "availability_zones"{
  default =[]
  type =list
  description ="available zones applied to mount target"
}

variable "customer_tags" {
   type =map
   default ={}
   description ="addition customer tags"
}
